### ISSUE TITLE
Cannot get rgbaString from new iro.Color()

### ISSUE THREAD

**Issue by DeveloperBlue** [jaames/iro-transparency-plugin#1]
When trying to get the rgbaString from a colorObject, it returns undefined as the value hasn't been set by the time I access the object. Printing the object shows that the value is there, but its added after the script is done executing.

```javascript

iro.use(iroTransparencyPlugin);

var colorReference = "#fff";
var temporaryColorObject = new iro.Color();
temporaryColorObject.set(colorReference);

console.log(temporaryColorObject);
console.log(temporaryColorObject["rgbaString"]);
/*
Output:

ct {_onChange: false, _value: {…}}
_onChange: false
_value: {h: 0, s: 0, v: 100}
alpha: (...)
hex8String: (...)
hexString: (...)
hsl: (...)
hslString: (...)
hsla: (...)
hslaString: (...)
hsv: (...)
hsva: (...)
rgb: (...)
rgbString: (...)
rgba: (...)
rgbaString: "rgba(255, 255, 255, undefined)" // Expected output
__proto__: Object

Followed by:
undefined
// Expected "rgba(255, 255, 255, undefined)"

*/
```

When printing the Color Object, it shows that the value is there, BUT it's set _after_ I print the object and the code has proceeded. Is there any way I can get the value without having to set timeouts and callbacks? Am I doing something wrong, shouldn't the value be there when I call .set()?

**Comment by jaames** [comment]
Hey @DeveloperBlue, thanks for opening this issue. Sorry to hear that you've encountered a problem with this.

Can I ask which browser you're working with? I'm struggling to reproduce this on my end (in macOS Chrome), with the following code:

```js
import iro from '@jaames/iro';
import iroTransparencyPlugin from 'iro-transparency-plugin';

iro.use(iroTransparencyPlugin);

let c = new iro.Color();

let ref = '#fff';
c.set(ref);

console.log(c); // {_onChange: false, _value: {…}, …}
console.log(c.rgbaString); // rgba(255, 255, 255, undefined)
console.log(c['rgbaString']); // rgba(255, 255, 255, undefined)
```

All of the color properties are using [Object.defineProperties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties), so they call getter/setter functions whenever the value is accessed or assigned. You can see the [source code for rgbaString here](https://github.com/jaames/iro-transparency-plugin/blob/master/src/index.js#L142). As far as I know, the only way this would return `undefined` is if all the properties aren't being defined properly somehow.

Just in case, please also double-check that you're using the latest versions of iro.js and the transparency plugin? `iro.version` should equal `"4.2.2"` and `iro.transparencyPlugin.version` should be `"1.0.1"`. Cheers!

**Comment by DeveloperBlue** [comment]
I ended up refactoring my code after my initial post, and after just trying again I don't seem to be running into the issue. I can only assume that **the error was on my part, sorry**.

However, before I close the issue, I've run into something else:

If I pass an _rgbaString_ to `iro.Color()`, and then get an _rgbaString_ or _hsva_ object, it throws away the alpha value and sets it to 0. This is unexpected behavior as one would want the alpha be preserved if given, and returned appropriately.

Also, if I attempt to get an _rgb**a**String_ or _hsv**a**_ object after setting `iro.Color()` with a color that does not have an alpha, like `#fff` or `rgb(255, 0, 120)`, the alpha is returned as `undefined`. I would argue it makes more sense to return the alpha as 1, to represent that it is a solid opaque color.

You can observe this here:
```javascript
iro.use(iroTransparencyPlugin);

console.log("Iro:", iro.version, "IroTP:", iro.transparencyPlugin.version);

var temporaryColorObject = new iro.Color();

function testColor(colorReference){
	
	temporaryColorObject.set(colorReference);
	console.log(colorReference, "-->", temporaryColorObject["rgbaString"]);
	console.log(colorReference, "-->", temporaryColorObject["hsva"]);
	console.log("======================================================");

}

testColor("#fff");
testColor("rgb(255, 102, 0)");
testColor("rgba(255, 102, 0, 0.55)");
testColor({h: 360, s: 240, v: 25});
testColor({h: 360, s: 120, v: 50, a: 0.2});
```

Iro: 4.2.2
Transparency plugin: 1.0.1
Chrome: Version 73.0.3683.86 [On Windows 7]

Would you rather I open a separate issue for this?

**Comment by jaames** [comment]
Ah, glad that error was resolved!

I agree that this has highlighted some strange behaviour with alpha handling that I didn't notice before.  It would definitely be appreciated if you could open another issue for this so I can remember to look at it when I have the time -- I'm currently meant to be taking a tiny hiatus from open-source stuff.
