### ISSUE TITLE
ReferenceError :: iroTransparencyPlugin is not defined

### ISSUE THREAD

**Issue by FryerTuck** [jaames/iro-transparency-plugin#4]
via **RequireJS**

```javascript
    require(['/libs/iro/iro-transparency-plugin.min.js'],(mod)=>
    {
        condole.log(mod); // undefined
    });
```
... or am I just drunk?

**Comment by jaames** [comment]
I'm not super familiar with RequireJS, but the library is defining itself correctly according to the RequireJS docs, you can see the call to `define()` in [iro-transparency-plugin.js on line 12](https://github.com/jaames/iro-transparency-plugin/blob/master/dist/iro-transparency-plugin.js#L12)

Maybe it's a RequireJS config or filepath issue?

**Comment by FryerTuck** [comment]
> I'm not super familiar with RequireJS, but the library is defining itself correctly according to the RequireJS docs, you can see the call to `define()` in [iro-transparency-plugin.js on line 12](https://github.com/jaames/iro-transparency-plugin/blob/master/dist/iro-transparency-plugin.js#L12)
> 
> Maybe it's a RequireJS config or filepath issue?

Thank you for the fast response; I've checked over and over, maybe I'm missing something.
I can paste some code i that would help, I'm not a RquireJS pro either, but, everything else works 100%, except this plug (which is so awesome BTW) - would save me so much time in reproducing from scratch.

**Comment by FryerTuck** [comment]
## Details

So, ok, if anybody can help solve this, it would be amazing, else I'll just have to post it on StackOverlow.

The function I made and use religiously through all my projects is rather simple, yet effective; it uses ***RequireJS*** for JS-files and it takes an array of paths with a call-back as the only 2 arguments, like this:

    requires(['iro:/libs/iro/iro.min.js', 'iro.iroTransparencyPlugin:/libs/iro/iro-transparency-plugin.js'],()=>
    {
        // ready
    });

- each path is split on `:`
- the `.` separated words are used for name assignment in order as given
- the first word in the `.`  list is used as a global, to make the library globally available

This **requires** function is used for CSS and fonts too, but, here is the code used for JavaScript:

```javascript
    let ps=p.split('.'); let pm=ps.shift(); let hp=twig(i); let pn=((ps.length<1)?pm:ps.pop());
    require.config({baseUrl:hp,paths:{[pm]:i}});
    require([i],function(m)
    {
        let n=this.nick; if(isVoid(m)&&isVoid(MAIN[n])){fail(`invalid "${n}" definition in: "${this.purl}"`);return};
        if(!!m){extend(MAIN)({[n]:m})}; d--; slf.done[this.purl]=1; a[this.nick]=m;
    }
    .bind({nick:pn,purl:i}));
```

### breakdown
- `p` is the "part" (string) that contains the dots, before the `:`
- `i` is the current item in the args-list of paths to load - after the `:`
- `ps` is now an array .: the "path-splitted" by `.` 
- `pm` is the "primary module-name" .: the first item in `ps`
- `hp` is the "home path" .: the folder in which the base-name (file-name) is
- `pn` is the "post name" .: the reference to check if it exists after loading
- `m` is the "module" (object/value) defined in the library, like: `module.exports = (function(){})`
- `isVoid` is just a function to check if something is either `undefined`, or `null`
- `MAIN` is simply the super-global `window` (or `global` in NodeJS)

With all that cleared up, the rest is pretty self explanatory, but the reasons for why it's like this is because some libraries do not use the CommonJS spec well (or at all), so, the functionality mitigates this by:
- checking if a value is returned that is NOT an "empty string", or `false`, or `undefined`
- if the above fails it checks if the name is assigned in the global scope
- if both checks fail then the library can not reliably be used by name, hence it MUST fail, gracefully

Whew, ok, sorry for the essay, I hope it's well received though, I must be missing something.

### conclusion
In the plugin code, I see:

```javascipt
    module.exports = factory();
```

I have no idea what `factory()` does, or where/what/how it gets the result though, further debugging could be enlightening.

Maybe I'm using RequireJS wrong, or maybe something else is causing an issue that I'm not aware of, but this is fairly simple stuff, and it should work though, any help would be appreciated, thanks.

**Comment by FryerTuck** [comment]
## Found possible cause

- in ***iro-transparency-plugin.js***
- on line: `10`
1. `module.exports` is assigned as the result of `factory()`
2.0. `factory` is the 2nd argument to the `webpackUniversalModuleDefinition` IIF
2.1. `factory` is the definition of the module, and expected to return a result as per no. 1 (above)
3.0. on line `433` `module.exports` is the result of `__webpack_require__(/*! ./index.js */"./index.js")`
3.1. this could work -if there is an `index.js` file that defines a structure, but if not exist if will be `undefined`

### introspection
The issue is 2-fold:
- `module.exports` is defined twice, 1st on line `433`, then on line `10`
- the result of `factory` is indeed `undefined` as it does not return anything

### solution
- have `factory` return the module as defined - if `__webpack_require__()` returns `undeined`

I hope this helps, I'll debug and fix it my side, and if I get it working I'll post an update here.

**Comment by jaames** [comment]
`module.exports` is just a Node thing as far as I know, RequireJS only uses `define()`. 

This library uses Webpack to bundle everything into an UMD module that's supposed to be compatible with multiple module loaders, including RequireJS. If it's not working for some reason then there's either an error with my Webpack config (https://github.com/jaames/iro-transparency-plugin/blob/master/webpack.config.js) or Webpack itself. 

If iro.js can be loaded properly then maybe it's worth moving this plugin to the same Rollup-based bundler it uses? Rollup seems to do a better job of bundling libraries anyway

**Comment by FryerTuck** [comment]
Thanks for the info, been debugging my assumptions and checking with RequireJS, and, there's nothing wrong with this plugin AT ALL.
I also think RequireJS is the culprit.
